Script started on Mon 26 Aug 2019 09:34:57 AM CDT
[?1034hbash-4.2$ man li
No manual entry for li
bash-4.2$ man ls
[?1049h[?1h=LS(1)                            User Commands                           LS(1)[m
[m
[1mNAME[0m[m
       ls - list directory contents[m
[m
[1mSYNOPSIS[0m[m
       [1mls[0m [[4mOPTION[24m]... [[4mFILE[24m]...[m
[m
[1mDESCRIPTION[0m[m
       List  information  about  the FILEs (the current directory by default).[m
       Sort entries alphabetically if none of [1m-cftuvSUX[0m nor [1m--sort[0m  is  speci‐[m
       fied.[m
[m
       Mandatory  arguments  to  long  options are mandatory for short options[m
       too.[m
[m
       [1m-a[0m, [1m--all[0m[m
              do not ignore entries starting with .[m
[m
       [1m-A[0m, [1m--almost-all[0m[m
              do not list implied . and ..[m
[m
       [1m--author[0m[m
[7m Manual page ls(1) line 1 (press h for help or q to quit)[27m[K[K              with [1m-l[0m, print the author of each file[m
[7m Manual page ls(1) line 2 (press h for help or q to quit)[27m[K[K[7m Manual page ls(1) line 2 (press h for help or q to quit)[27m[K[K[7m Manual page ls(1) line 2 (press h for help or q to quit)[27m[K[K[7mNo next tag  (press RETURN)[27m[24;1H[K[K[7m Manual page ls(1) line 2 (press h for help or q to quit)[27m[K[K[m
[7m Manual page ls(1) line 5 (press h for help or q to quit)[27m[K[K[?1l>[?1049lbash-4.2$ cd
bash-4.2$ pwd
/home/u2/jdg0058
bash-4.2$ ls
commands.script  ntuser.cmd  sample.script  Task1  typescript
bash-4.2$ mkdir p1
bash-4.2$ cp
cp: missing file operand
Try 'cp --help' for more information.
bash-4.2$ cp[K[Kcd .
bash-4.2$ exit[K[K[K[Kls
commands.script  ntuser.cmd  p1  sample.script	Task1  typescript
bash-4.2$ cd p1
bash-4.2$ ls
bash-4.2$ cd .
bash-4.2$ ls
bash-4.2$ exit[K[K[K[Kcd ..
bash-4.2$ ls
commands.script  ntuser.cmd  p1  sample.script	Task1  typescript
bash-4.2$ cp task1[K[K[K[K[KTask1 p1
bash-4.2$ ls
commands.script  ntuser.cmd  p1  sample.script	Task1  typescript
bash-4.2$ cd p1
bash-4.2$ ls
Task1
bash-4.2$ cd..[K[K ..
bash-4.2$ ls
commands.script  ntuser.cmd  p1  sample.script	Task1  typescript
bash-4.2$ mv typescript p1
bash-4.2$ ls
commands.script  ntuser.cmd  p1  sample.script	Task1
bash-4.2$ cd p1
bash-4.2$ ls
Task1  typescript
bash-4.2$ cd ..
bash-4.2$ cd p1
bash-4.2$ ;[Kls
Task1  typescript
bash-4.2$ rm Task1
bash-4.2$ ls
typescript
bash-4.2$ cd ..
bash-4.2$ mkdir deleteThis
bash-4.2$ ls
commands.script  deleteThis  ntuser.cmd  p1  sample.script  Task1
bash-4.2$ rmdir deleteThis
bash-4.2$ ls
commands.script  ntuser.cmd  p1  sample.script	Task1
bash-4.2$ chmod Task1
chmod: missing operand after ‘Task1’
Try 'chmod --help' for more information.
bash-4.2$ chmod u=rwx,g=rwx,o=r Task1
bash-4.2$ clear
[3;J[H[2Jbash-4.2$ top
[?1h=[?25l[H[2J(B[mtop - 09:42:55 up 9 days, 21:46,  5 users,  load average: 1.00, 0.99, 1.03(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 312 (B[m[39;49mtotal,(B[m[39;49m[1m   2 (B[m[39;49mrunning,(B[m[39;49m[1m 310 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  6.6 (B[m[39;49mus,(B[m[39;49m[1m  1.9 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 91.5 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m 24509152 (B[m[39;49mtotal,(B[m[39;49m[1m 19099108 (B[m[39;49mfree,(B[m[39;49m[1m   932712 (B[m[39;49mused,(B[m[39;49m[1m  4477332 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m 12386300 (B[m[39;49mtotal,(B[m[39;49m[1m 12386300 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m 23040472 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m[1m20623 yzz0115   20   0  237944 110828   2092 R  81.0  0.5  24:31.90 python      (B[m[39;49m[K
(B[m[1m22625 jdg0058   20   0  168480   2540   1664 R  14.3  0.0   0:00.08 top         (B[m[39;49m[K
(B[m    1 root      20   0  194196   7308   4188 S   0.0  0.0   3:56.73 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.52 kthreadd    (B[m[39;49m[K
(B[m    3 root      20   0       0      0      0 S   0.0  0.0   0:00.53 ksoftirqd/0 (B[m[39;49m[K
(B[m    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    8 root      rt   0       0      0      0 S   0.0  0.0   0:00.09 migration/0 (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      20   0       0      0      0 S   0.0  0.0   1:36.36 rcu_sched   (B[m[39;49m[K
(B[m   11 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-dr+ (B[m[39;49m[K
(B[m   12 root      rt   0       0      0      0 S   0.0  0.0   0:07.36 watchdog/0  (B[m[39;49m[K
(B[m   13 root      rt   0       0      0      0 S   0.0  0.0   0:02.70 watchdog/1  (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.61 migration/1 (B[m[39;49m[K
(B[m   15 root      20   0       0      0      0 S   0.0  0.0   0:00.24 ksoftirqd/1 (B[m[39;49m[K
(B[m   17 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:+ (B[m[39;49m[K
(B[m   19 root      rt   0       0      0      0 S   0.0  0.0   0:02.17 watchdog/2  (B[m[39;49m[K
(B[m   20 root      rt   0       0      0      0 S   0.0  0.0   0:00.23 migration/2 (B[m[39;49m[K[H(B[mtop - 09:42:58 up 9 days, 21:46,  5 users,  load average: 1.00, 0.99, 1.03(B[m[39;49m(B[m[39;49m[K

%Cpu(s):(B[m[39;49m[1m  6.3 (B[m[39;49mus,(B[m[39;49m[1m  0.0 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 93.7 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m 24509152 (B[m[39;49mtotal,(B[m[39;49m[1m 19098692 (B[m[39;49mfree,(B[m[39;49m[1m   933124 (B[m[39;49mused,(B[m[39;49m[1m  4477336 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m 12386300 (B[m[39;49mtotal,(B[m[39;49m[1m 12386300 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m 23040056 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K

(B[m[1m20623 yzz0115   20   0  237944 110828   2092 R  99.7  0.5  24:34.91 python      (B[m[39;49m[K
(B[m 2439 root      20   0  263700  18988  17468 S   0.3  0.1   0:38.83 rsyslogd    (B[m[39;49m[K
(B[m 4165 root      20   0       0      0      0 S   0.3  0.0   0:00.02 kworker/0:0 (B[m[39;49m[K
(B[m    1 root      20   0  194196   7308   4188 S   0.0  0.0   3:56.73 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.52 kthreadd    (B[m[39;49m[K
(B[m    3 root      20   0       0      0      0 S   0.0  0.0   0:00.53 ksoftirqd/0 (B[m[39;49m[K
(B[m    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    8 root      rt   0       0      0      0 S   0.0  0.0   0:00.09 migration/0 (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      20   0       0      0      0 S   0.0  0.0   1:36.36 rcu_sched   (B[m[39;49m[K
(B[m   11 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-dr+ (B[m[39;49m[K
(B[m   12 root      rt   0       0      0      0 S   0.0  0.0   0:07.36 watchdog/0  (B[m[39;49m[K
(B[m   13 root      rt   0       0      0      0 S   0.0  0.0   0:02.70 watchdog/1  (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.61 migration/1 (B[m[39;49m[K
(B[m   15 root      20   0       0      0      0 S   0.0  0.0   0:00.24 ksoftirqd/1 (B[m[39;49m[K
(B[m   17 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:+ (B[m[39;49m[K
(B[m   19 root      rt   0       0      0      0 S   0.0  0.0   0:02.17 watchdog/2  (B[m[39;49m[K[H(B[mtop - 09:43:02 up 9 days, 21:46,  5 users,  load average: 1.00, 0.99, 1.03(B[m[39;49m(B[m[39;49m[K


KiB Mem :(B[m[39;49m[1m 24509152 (B[m[39;49mtotal,(B[m[39;49m[1m 19098700 (B[m[39;49mfree,(B[m[39;49m[1m   933108 (B[m[39;49mused,(B[m[39;49m[1m  4477344 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m 12386300 (B[m[39;49mtotal,(B[m[39;49m[1m 12386300 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m 23040064 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K

(B[m[1m20623 yzz0115   20   0  238200 110828   2092 R 100.0  0.5  24:37.93 python      (B[m[39;49m[K
(B[m 5237 gdm       20   0 4662116 282404  55660 S   1.3  1.2  37:19.02 gnome-shell (B[m[39;49m[K
(B[m[1m22625 jdg0058   20   0  168480   2616   1716 R   0.7  0.0   0:00.10 top         (B[m[39;49m[K













[?25l[H(B[mtop - 09:43:04 up 9 days, 21:46,  5 users,  load average: 1.00, 0.99, 1.03(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 312 (B[m[39;49mtotal,(B[m[39;49m[1m   2 (B[m[39;49mrunning,(B[m[39;49m[1m 310 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  6.2 (B[m[39;49mus,(B[m[39;49m[1m  0.0 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 93.7 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m 24509152 (B[m[39;49mtotal,(B[m[39;49m[1m 19098864 (B[m[39;49mfree,(B[m[39;49m[1m   932928 (B[m[39;49mused,(B[m[39;49m[1m  4477360 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m 12386300 (B[m[39;49mtotal,(B[m[39;49m[1m 12386300 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m 23040236 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m[1m20623 yzz0115   20   0  238200 110932   2092 R 100.0  0.5  24:40.92 python      (B[m[39;49m[K
(B[m 6304 gdm       20   0  715304  18376   9444 S   0.3  0.1   4:33.25 gsd-color   (B[m[39;49m[K
(B[m[1m22625 jdg0058   20   0  168480   2616   1716 R   0.3  0.0   0:00.11 top         (B[m[39;49m[K
(B[m    1 root      20   0  194196   7308   4188 S   0.0  0.0   3:56.73 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.52 kthreadd    (B[m[39;49m[K
(B[m    3 root      20   0       0      0      0 S   0.0  0.0   0:00.53 ksoftirqd/0 (B[m[39;49m[K
(B[m    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    8 root      rt   0       0      0      0 S   0.0  0.0   0:00.09 migration/0 (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      20   0       0      0      0 S   0.0  0.0   1:36.36 rcu_sched   (B[m[39;49m[K
(B[m   11 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-dr+ (B[m[39;49m[K
(B[m   12 root      rt   0       0      0      0 S   0.0  0.0   0:07.36 watchdog/0  (B[m[39;49m[K
(B[m   13 root      rt   0       0      0      0 S   0.0  0.0   0:02.70 watchdog/1  (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.61 migration/1 (B[m[39;49m[K
(B[m   15 root      20   0       0      0      0 S   0.0  0.0   0:00.24 ksoftirqd/1 (B[m[39;49m[K
(B[m   17 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:+ (B[m[39;49m[K
(B[m   19 root      rt   0       0      0      0 S   0.0  0.0   0:02.17 watchdog/2  (B[m[39;49m[K[?1l>[25;1H
[?12l[?25h[Kbash-4.2$ who
yzz0115  pts/0        2019-08-20 08:55 (ettin.eng.auburn.edu)
dtj0003  pts/1        2019-08-26 07:58 (ettin.eng.auburn.edu)
tmw0029  pts/2        2019-08-26 09:26 (ettin.eng.auburn.edu)
jdg0058  pts/3        2019-08-26 09:31 (ettin.eng.auburn.edu)
jdg0058  pts/4        2019-08-26 09:34
bash-4.2$ nproc
16
bash-4.2$ exit
exit

Script done on Mon 26 Aug 2019 09:43:48 AM CDT
